#COPY THIS CONFIG FILE IN SCHEDULER/SOURCE 
CONNECTION_TIME_OUT=10
READ_TIME_OUT=80
WRITE_TIME_OUT=10
FETCH_ROW_SET=5
PRINCIPALS=MLCL
END_POINT_URL=https://staging1.pmgatishakti.gov.in/MSTCRestApiService/authenticate
END_POINT_URL_RES=https://staging1.pmgatishakti.gov.in/MSTCRestApiService/MSTCapi/uploadAuctionLegacyJsonFile
CALLING_PAGE=https://cma.mstcauction.com/auctionhome/mlcl_data_integration.jsp
USERNAME=MSTC_User
PASSWORD=MSTC@User